function create_default_config_xlsx(xlsx_path)
%CREATE_DEFAULT_CONFIG_XLSX  生成批量实验配置 xlsx（含示例配置）
%
%   create_default_config_xlsx()
%   create_default_config_xlsx('a.输入/批量实验配置.xlsx')

    if nargin < 1 || isempty(xlsx_path)
        xlsx_path = fullfile('a.输入', '批量实验配置.xlsx');
    end

    [p, ~, ~] = fileparts(xlsx_path);
    if ~isempty(p) && ~isfolder(p)
        mkdir(p);
    end

    if isfile(xlsx_path)
        delete(xlsx_path);
    end

    % ==================== Sheet 1: 实验组合 ====================
    %  示例：
    %    G1 — US_Backbone 拓扑下 4 种方法对比，重复 3 次
    %    G2 — Abilene 拓扑下 4 种方法对比，重复 3 次
    %    G3 — RDA 方法的参数调优（3 个参数组），重复 3 次
    experiments = table( ...
        ["G1"; "G1"; "G1"; "G1"; ...
         "G2"; "G2"; "G2"; "G2"; ...
         "G3"; "G3"; "G3"], ...
        ["US_Backbone"; "US_Backbone"; "US_Backbone"; "US_Backbone"; ...
         "Abilene"; "Abilene"; "Abilene"; "Abilene"; ...
         "US_Backbone"; "US_Backbone"; "US_Backbone"], ...
        ["ResourceAndDelayAwareOnline"; "nodeFirst"; "shortestPathFirstWithLoadBalancing"; "RSA"; ...
         "ResourceAndDelayAwareOnline"; "nodeFirst"; "shortestPathFirstWithLoadBalancing"; "RSA"; ...
         "ResourceAndDelayAwareOnline"; "ResourceAndDelayAwareOnline"; "ResourceAndDelayAwareOnline"], ...
        ["default"; "default"; "default"; "default"; ...
         "default"; "default"; "default"; "default"; ...
         "default"; "aggressive"; "conservative"], ...
        ["1"; "1"; "1"; "1"; ...
         "1"; "1"; "1"; "1"; ...
         "1,2"; "1,2"; "1,2"], ...
        [3; 3; 3; 3; ...
         3; 3; 3; 3; ...
         3; 3; 3], ...
        [1; 1; 1; 1; ...
         1; 1; 1; 1; ...
         0; 0; 0], ...
        'VariableNames', {'group_id','topo_name','method_name','param_group', ...
                          'request_set_ids','repeat_count','enabled'});
    writetable(experiments, xlsx_path, 'Sheet', '实验组合');

    % ==================== Sheet 2: 拓扑配置 ====================
    topos = table( ...
        ["US_Backbone"; "Abilene"; "Cogentco"; "Chinanet"], ...
        ["US_Backbone"; "Abilene"; "Cogentco"; "Chinanet"], ...
        [80; 40; 60; 50], [120; 80; 100; 90], ...
        [80; 40; 60; 50], [120; 80; 100; 90], ...
        [160; 100; 140; 120], [320; 200; 280; 240], ...
        'VariableNames', {'topo_name','topo_func','minm','maxm','minc','maxc','minb','maxb'});
    writetable(topos, xlsx_path, 'Sheet', '拓扑配置');

    % ==================== Sheet 3: 请求配置 ====================
    reqs = table( ...
        ["US_Backbone"; "Abilene"; "Cogentco"; "Chinanet"], ...
        [100; 100; 100; 100], ...
        [5; 5; 5; 5], ...
        [8; 8; 8; 8], ...
        [3; 3; 3; 3], ...
        [8; 24; 12; 10], ...
        [2; 6; 3; 3], ...
        [4; 4; 4; 4], ...
        [1; 1; 1; 1], ...
        [250; 100; 200; 180], ...
        [100; 50; 80; 70], ...
        'VariableNames', {'topo_name','requests_num','destNode_count','vnftype_num','vnf_num', ...
                          'maxbw','minbw','maxnr','minnr','maxt','mint'});
    writetable(reqs, xlsx_path, 'Sheet', '请求配置');

    % ==================== Sheet 4: 方法配置 ====================
    methods = table( ...
        ["shortestPathFirstWithLoadBalancing"; "nodeFirst"; "RSA"; "ResourceAndDelayAwareOnline"], ...
        ["STB"; "NIF"; "RSA"; "RDA"], ...
        ["shortestPathFirstWithLoadBalancing"; "nodeFirst"; "RSA"; "ResourceAndDelayAwareOnline"], ...
        ["sortedRequests"; "requests"; "sortedRequests"; "sortedRequests"], ...
        ["FixedTreePlan"; "FixedTreePlan"; "FixedTreePlan"; "FixedTreePlan"], ...
        ["generateDeployPlan"; "generateDeployPlan"; "generateDeployPlan"; "generateDeployPlan"], ...
        [0; 0; 0; 1], ...
        'VariableNames', {'method_name','display_name','deploy_func','requests_type', ...
                          'fixed_func','sorted_func','online_mode'});
    writetable(methods, xlsx_path, 'Sheet', '方法配置');

    % ==================== Sheet 5: 方法参数组 ====================
    %  示例：为 RDA 方法定义 3 个参数组用于调优对比
    %    default      — 均衡配置
    %    aggressive   — 高共享权重，激进复用 VNF
    %    conservative — 高拥塞权重，保守选路避免热点
    params = table( ...
        ["ResourceAndDelayAwareOnline"; "ResourceAndDelayAwareOnline"; "ResourceAndDelayAwareOnline"], ...
        ["default"; "aggressive"; "conservative"], ...
        [5; 8; 3], ...
        [5; 8; 3], ...
        [1; 3; 0.5], ...
        [1.0; 0.5; 2.0], ...
        [3.0; 1.0; 5.0], ...
        [0; 0; 0.2], ...
        'VariableNames', {'method_name','param_group','candLinkNum','candNodeNum', ...
                          'shareWeight','congWeight','delayWeight','shareDecayMin'});
    writetable(params, xlsx_path, 'Sheet', '方法参数组');

    % ==================== Sheet 6: 全局设置 ====================
    keys = ["rng_seed_base"; "output_dir"; "summary_xlsx"; "plot_data_xlsx"; ...
            "fig_visible"; "save_svg"; "save_mat"; "svg_background"; ...
            "fig_width"; "fig_height"; "line_width"; "font_size"; ...
            "slack_mode"; "e2e_source"];
    vals = ["42"; "c.输出"; "实验结果汇总.xlsx"; "绘图数据.xlsx"; ...
            "off"; "1"; "0"; "none"; ...
            "800"; "600"; "1.8"; "12"; ...
            "ratio"; "auto"];
    descs = [ ...
        "随机种子基数，保证实验可重复"; ...
        "输出根目录"; ...
        "结果汇总文件名（在 output_dir 下）"; ...
        "绘图数据文件名（在 output_dir 下）"; ...
        "绘图时是否显示窗口 (on/off)"; ...
        "是否保存 SVG 图表 (1=是, 0=否)"; ...
        "是否保存 MAT 结果文件 (1=是, 0=否)"; ...
        "SVG 背景色 (none=透明)"; ...
        "默认图宽（像素）"; ...
        "默认图高（像素）"; ...
        "曲线线宽"; ...
        "图表字号"; ...
        "裕量模式 (ratio=比例, abs=绝对值)"; ...
        "端到端时延来源 (auto=自动选择)"];
    global_cfg = table(keys, vals, descs, 'VariableNames', {'key','value','description'});
    writetable(global_cfg, xlsx_path, 'Sheet', '全局设置');

    fprintf('已生成示例配置: %s\n', xlsx_path);
end
